// VS Code REST CLIENT EKLENTİSİ İLE İLGİLİ DÜZENLEMELER BURADA


@host= http://localhost:8000  
#host bağlı olcağın url
# @query=? gönderilmek istenen sorgu
GET {{host}}/product HTTP/1.1

###
GET {{host}}/order HTTP/1.1

###
GET {{host}}/user HTTP/1.1

content-type: application/json

